# Generated by Django 3.2.3 on 2021-09-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('body', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=8)),
            ],
        ),
    ]
