# Generated by Django 3.2.3 on 2021-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
